hs.loadSpoon("AllBrightness")
spoon.AllBrightness:start()

hs.loadSpoon("RoundedCorners")
spoon.RoundedCorners:start()

meh = { "ctrl", "alt", "shift" }

hs.hotkey.bind(meh, "F", function()
	hs.application.launchOrFocus("Finder")
end)
hs.hotkey.bind(meh, "M", function()
	hs.application.launchOrFocus("Messages")
end)
hs.hotkey.bind(meh, "C", function()
	hs.application.launchOrFocus("Google Chrome")
end)
hs.hotkey.bind(meh, "S", function()
	hs.application.launchOrFocus("Safari")
end)
hs.hotkey.bind(meh, "N", function()
	hs.application.launchOrFocus("Notes")
end)
hs.hotkey.bind(meh, "P", function()
	hs.application.launchOrFocus("Spotify")
end)
hs.hotkey.bind(meh, "K", function()
	hs.application.launchOrFocus("Docker")
end)
hs.hotkey.bind(meh, "D", function()
	hs.application.launchOrFocus("Visual Studio Code")
end)
hs.hotkey.bind(meh, "T", function()
	hs.application.launchOrFocus("iTerm")
end)
